#!/bin/sh

# Should be platform neutral - at least working on Linux and Windows
USER_NAME="datasci"
HOME_DIR="/home/$USER_NAME"

# Users home is mounted as home
# --rm will remove the container as soon as it ends
echo "Linking: ${HOME}/Workspace to container Workspace ${HOME_DIR}/Workspace"
docker run --rm \
    --net host \
    -i -t \
    -e ${HOME} \
    -w $HOME_DIR \
    -p 8888:8888 \
    base-data-science-cpu