#!/bin/sh

# Should be platform neutral - at least working on Linux and Windows
USER_NAME="datasci"
HOME_DIR="/home/$USER_NAME"

# Users home is mounted as home
# --rm will remove the container as soon as it ends
echo "Linking: ${HOME}/Workspace to container Workspace ${HOME_DIR}/Workspace"
docker run --rm \
    --net host \
    -i -t \
    -v ${HOME}/Workspace:${HOME_DIR}/Workspace \
    -v /tmp/.X11-unix:/tmp/.X11-unix \
    -v $HOME/Downloads:/home/Downloads \
    -v /dev/shm:/dev/shm \
    -e DISPLAY=unix${DISPLAY} \
    -e HHHOME=${HOME} \
    -w $HOME_DIR \
    -p 8888:8888 \
    -p 6006:6006 \
    --device /dev/snd \
    --name $USER_NAME \
    qinetiq/wooweb-presentation-cpu:latest