#!/bin/sh

USER_NAME="datasci"
HOME_DIR="/home/$USER_NAME"

# Users home is mounted as home
# --rm will remove the container as soon as it ends
docker run --rm \
    -i -t \
    -v $HOME/Documents:${HOME_DIR}/Documents \
    -v $HOME/Downloads:${HOME_DIR}/Downloads \
    -v $HOME/Workspace:${HOME_DIR}/Workspace \
    -w $HOME_DIR \
    -p 8888-9000:8888-9000 \
    -v /tmp/.X11-unix:/tmp/.X11-unix \
    -e DISPLAY=unix${DISPLAY} \
    --device /dev/snd \
    -v /dev/shm:/dev/shm \
    --device /dev/dri \
    --security-opt seccomp:unconfined \
    --cap-add=SYS_ADMIN \
    -e "container=docker" \
    -v /sys/fs/cgroup:/sys/fs/cgroup:ro \
    --privileged=true \
    --name docker-redhawk \
    qinetiq/redhawk-data-science:latest
    
