#!/bin/sh

USER_NAME="datasci"
HOME_DIR="/home/$USER_NAME"

# Users home is mounted as home
# --rm will remove the container as soon as it ends
docker run --rm \
    -i -t \
    -v $HOME/Documents:${HOME_DIR}/Documents \
    -v $HOME/Downloads:${HOME_DIR}/Downloads \
    -w $HOME_DIR \
    -v /tmp/.X11-unix:/tmp/.X11-unix \
    -e DISPLAY=unix$DISPLAY \
    -e ${HOME} \
    -p 8888-9000:8888-9000 \
    -p 8787:8787 \
    -p 8000:8000 \
    --device /dev/dri \
    --name ubuntu-base-data-science \
    qinetiq/ubuntu-base-data-science:latest